# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.0
    hooks:
      - id: gitleaks
        args:
        - '--verbose'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
    - id: ruff-check
      files: ^python/
      args: [--output-format, github, --fix]
    - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
    - id: typos
      files: ^python/
      args: [--force-exclude]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
    - id: clang-format
      files: \.(cc|cpp|h|hpp)$
      types_or: [c++]
      args: [--style=file, --verbose]
      exclude: ^cpp/thirdparty/

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [
          --types,feat,fix,docs,style,refactor,test,chore,perf,ci,build,revert,
          --scope-optional
        ]

  - repo: local
    hooks:
      - id: spotless-java-info
        name: Spotless java-info
        entry: bash -c 'cd maven-projects/info && mvn spotless:apply'
        language: system
        files: ^maven-projects/info/
        pass_filenames: false
        require_serial: true

      - id: spotless-java-ffi
        name: Spotless java-ffi
        entry: bash -c 'cd maven-projects/java && mvn spotless:apply'
        language: system
        files: ^maven-projects/java/
        pass_filenames: false
        require_serial: true

      - id: spotless-spark
        name: Spotless spark
        entry: bash -c 'cd maven-projects/spark && mvn spotless:apply'
        language: system
        files: ^maven-projects/spark/
        pass_filenames: false
        require_serial: true