# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: GraphAr C++ CI Nightly

on:
  workflow_dispatch:
  schedule:
    # The notifications for scheduled workflows are sent to the user who
    # last modified the cron syntax in the workflow file.
    # Trigger the workflow at 03:00(CST) every day.
    - cron:  '00 19 * * *'
jobs:
  GraphAr-ubuntu-arrow-from-source:
    if: ${{ github.ref == 'refs/heads/main' && github.repository == 'apache/incubator-graphar' }}
    runs-on: ubuntu-latest
    env:
      GAR_TEST_DATA: ${{ github.workspace }}/graphar-testing/
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: Cache for ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ matrix.os }}-build-ccache-${{ hashFiles('**/git-modules.txt') }}
        restore-keys: |
          ${{ matrix.os }}-build-ccache-

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libboost-graph-dev ccache libcurl4-openssl-dev

        # install Catch2 v3
        git clone --branch v3.6.0 https://github.com/catchorg/Catch2.git --depth 1
        pushd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        popd

        git clone https://github.com/apache/incubator-graphar-testing.git $GAR_TEST_DATA --depth 1

    - name: CMake-debug
      run: |
        mkdir build-debug
        pushd build-debug
        cmake ../cpp -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_ARROW_FROM_SOURCE=ON
        popd

    - name: Build GraphAr-debug
      run: |
        pushd build-debug
        make -j$(nproc)
        make graphar-ccache-stats
        popd
        
    - name: Test-debug
      run: |
        pushd build-debug
        ctest --output-on-failure
        popd


    - name: CMake-release
      run: |
        mkdir build-release
        pushd build-release
        cmake ../cpp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_ARROW_FROM_SOURCE=ON
        popd

    - name: Build GraphAr-release
      run: |
        pushd build-release
        make -j$(nproc)
        make graphar-ccache-stats
        popd

    - name: Test-release
      run: |
        pushd build-release
        ctest --output-on-failure
        popd
